#' Obtain the Holmes_bcell data
#'
#' Obtain the germinal centre B-cell CITE-seq data from Holmes \emph{et al.}
#' (2020).
#'
#'@details
#'CITE-seq of germinal centre B-cells isolated from tonsil tissue of a single
#'donor.  Germinal B-cells (CD3-/IgD-/CD38+) were sorted using FACS.
#'
#'Counts for RNA and ADT reads were generated by CellRanger v2.1.0.
#'
#'Data were downloaded from
#'\url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE139891}
#'
#'scRNA-seq was performed on B cells from two donors.  These samples are not
#'included in this data set.
#'
#'@references
#'Holmes, Antony B., et al. "Single-cell analysis of germinal-center B cells
#'informs on lymphoma cell of origin and outcome." Journal of Experimental
#'Medicine 217.10 (2020).
#'\doi{doi: 10.1084/jem.20200483}
#'@export
Holmes_bcell <- function(){

}
